notifications:
  webhooks:
    on_success: always
    on_failure: always
    on_start: never
    on_cancel: always
    on_error: always
    urls:
      - secure: jI9aQSaImCrNXQq0OCZyIWiYXKPw/5IxHmptZbgXn8fC+OCBJ8ZWD3hR2z2MF6VZBi1QXvQn5QXBYWy2wg74dIuexKcyURfYkCFh6oNdbxb2/6eKk5GzHAIhjmJPMX/jgBziW8mn+0hhabCX/h27tueFF8M3IVnlBOw1rR0FLO+bomRelxoUkchTGGT1NcJwtTRlIVeOcnvhFsp9BhZBTObQh5LEMTI29EPDavLF/QHxGAXNtndbTjBVZrMkQGcu22yxlETLZHCpEHUVcI1eCWco/6BJFvkOzgQF+jpDQTkIxriMko+oPR1dxm7B0DZ3UtceL+77En6CSshi/8jKZ25dkx+OfYckC2PMRVZ1TKSO4osjetBo07abPmjTTaAP67biF66eOYL4wP1bY+C2WVDO11lqythBxMXKkVX6jk7NIRKQvdJAFwrhxDPad079v9TeQwjiRUCcpSRtX5EjaQWiFW+ilDsLKUHIaoiuinDNsLG7yOcI9AJvzat1sHQ73nRziJWRLwPFl+7fE3QZyDhl29KaK32ebbM0RS1WgH0L4xRxjimTbTUKjVaqp9fEi0+TnpJx9dJRfiXOSm454IcBoTgO2f2uvlpt4d6UIU6DJ2DUeXIA+OUgShBaE0gJlJUwhn+sAPu6kRzWbtr7enpPVbeRJ3PSBli1DvBoep8=
