name: reviewdog
on: [ pull_request ]
jobs:
  eslint:
    name: eslint via reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKENS }}
          reporter: github-pr-check
          eslint_flags: 'eslint src/ --ext .ts'
