name: reviewdog
on: [ pull_request ]
jobs:
  lint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: eslint-review
        uses: ./.github/actions/action-eslint
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: 'src --ext .ts'
      - name: eslint-check
        uses: ./.github/actions/action-eslint
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          eslint_flags: 'src --ext .ts'
